config/routes.rb
Rails.application.routes.draw do
  get 'todos/index'

  get 'todos_delete', to: 'todos#delete', as: :delete
  match "todos/add" => "todos#add", :via => :post
  match 'todos/complete' => 'todos#complete', :via => :post

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :todo_item, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todo_items = Todo.all
    @new_todo = Todo.new
  end

  def delete
  end

  def add
    todo = Todo.create(:todo_item => params[:todo][:todo_item])
    unless todo.valid?
      flash[:error] = todo.errors.full_messages.join("<br>").html_safe
    else
      #set flash[:success] to "Todo added successfully"
    end
    redirect_to :action => 'index'
  end

  def complete
    params[:todos_checkbox].each do |check|
      todo_id = check
      t = Todo.find_by_id(todo_id)
      t.update_attribute(:completed, true)
    end
    redirect_to :action => 'index'
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/Todo.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "AppCodelearn" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">AppCodelearn</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppCodelearn</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>


<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">Just Did it</a>
  </div>
</div>

<% if !flash[:error].nil? %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert" >×</button>
      <strong><%= flash[:error] %></strong>
    </div>
<% end %>

<% if flash[:success] %>
    <div class="alert alert-success">
      #show flash[:success] message here
    </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/todos/delete.html.erb
<div class="container">
  <p>Todo successfully deleted</p>
  <a href="/todos/index">Back</a>

</div>

app/views/todos/index.html.erb
<title>Shared Todo App </title>

<div class="container">
  <div>
    <p>All your todos here</p>
    <%= form_for @new_todo, :url => { :action => "add" }  do |f|  %>
        <%= f.text_field  :todo_item %>
        <%= f.submit "Add todo", class: "btn btn-primary" %>
        <%end%>
  </div>
  <div class="row">
    <div class="span4">
      <h1>Shared Todo App</h1>
      <hr>
      <p>All your todos here</p>
      <div class="well">
        <%= form_tag("/todos/complete/", :method => "post") do %>
            <ul style="list-style-type:none;">
              <% @todo_items.each do |t| %>
                  <% if t.completed == true %>
                      <li style="color:grey;"> <%= check_box_tag  "todos_checkbox[]",t.id %>  <strong><%= t.todo_item %></strong> </li>
                  <% else %>
                      <li> <%= check_box_tag  "todos_checkbox[]",t.id %> <%= t.todo_item %>  </li>
                  <% end %>
              <%end%>
            </ul>
            <%= submit_tag("Complete Todos", :class=>"btn btn-success") %>
        <%end %>
      </div>
    </div>
  </div>


  <%= link_to "Delete last todo", delete_path %>


</div>